### ISSUE TITLE
TypeError: ufunc 'isnan' not supported

### ISSUE THREAD

**Issue by StephanTir** [MSingerLab/COMETSC#5]
Hi,

I get the following error when running comet (Running the example data files works fine):

```
(Virtualenv_3_6) bqdyn253_025:data stirier$ Comet tabmarker.txt tabvis.txt tabcluster.txt output/
Started on 2019-10-18T18:23:55.076413
Reading data...
Traceback (most recent call last):
  File "/Users/stirier/Virtualenv_3_6/bin/Comet", line 8, in <module>
    sys.exit(main())
  File "/Users/stirier/Virtualenv_3_6/lib/python3.6/site-packages/Comet/__main__.py", line 795, in main
    skipvis=skipvis)
  File "/Users/stirier/Virtualenv_3_6/lib/python3.6/site-packages/Comet/__main__.py", line 100, in read_data
    if np.isnan(cls_ser[0]):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

I extract the normalised count from Seurat:

```
input_data <- GetAssayData(object = BM1, slot = "data", assay = "SCT")
write.table(x = input_data, quote=F, sep="\t", row.names = T, col.names = NA, file = "/Volumes/ag-rippe/NGS_Stephan/HIPO2_K43R/General_Scripts/Comet/data/tabmarker.txt")
```

Do you have any idea what is wrong?

Thanks in advance!

Best

Stephan

**Comment by Cnrdelaney** [comment]
Hi Stephan,
This error usually occurs when the cluster file contains non-integer assignments. I would check this and if the error still occurs let me know!

**Comment by StephanTir** [comment]
Yes, that's it! Thanks a lot!
